# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

# test_that("fct_render_prettyprint works", {
#   expect_true(inherits(fct_render_prettyprint, "function")) 
# })
