# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

# test_that("fct_xlsfrom_language works", {
#   expect_true(inherits(fct_xlsfrom_language, "function")) 
# })
