# WARNING - Generated by {fusen} from dev/function_documentation.Rmd: do not edit by hand

#' fct_xlsfrom_language
#' 
#' Retrieve a factor with all label languages used in a specific xlsform.
#' Used in the app to retrieve the language to consider based on the form
#' 
#' @param xlsformpath path to the file with xlsform
#' 
#' @importFrom readxl read_excel
#' @importFrom dplyr rename mutate filter pull
#' @importFrom stringr str_remove
#' 
#' @return label_language
#' @export
#' @examples
#' ## With different language
#' fct_xlsfrom_language( xlsformpath = system.file("demo.xlsx",
#'                                                 package = "XlsFormUtil"))
#'
#' ## without language
#' fct_xlsfrom_language( xlsformpath = system.file("KoBoXLSFormExamples.xlsx",
#'                                                 package = "XlsFormUtil"))

fct_xlsfrom_language <- function(xlsformpath){

  # xlsformpath <- "inst/RMS_CAPI_v2_en_es_fr.xlsx"
  survey <- readxl::read_excel(xlsformpath, sheet = "survey")
  
  ## Get all variables starting with language
  label_language <- names(survey) |>
              as.data.frame() |>
              dplyr::rename(  "label_language" = "names(survey)" ) |>
              dplyr::filter(grepl("label", label_language)) |>
              dplyr::mutate( label_language = stringr::str_remove(label_language,
                                                                  "label"))|>
              dplyr::mutate( label_language = stringr::str_remove(label_language,
                                                                  "::"))
  ## in case now language was defined... return NULL
  if(nlevels(as.factor(label_language$label_language)) == 1 )
  { label_language = NULL} else 
      { label_language <- label_language |> dplyr::pull()}
  
  return(label_language )
}
